DROP DATABASE IF EXISTS [p3_final];

CREATE DATABASE [p3_final];

USE [p3_final];

DROP TABLE IF EXISTS [dbo].[EX2_TIPOS_LICENCIAS];

CREATE TABLE [dbo].[EX2_TIPOS_LICENCIAS] (
  TIPO_LICENCIA_ID INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  DESCRIPCION VARCHAR(255) NOT NULL,
  PRIMARY KEY (TIPO_LICENCIA_ID)
);

DROP TABLE IF EXISTS [dbo].[EX2_CONDUCTORES] ;

CREATE TABLE [dbo].[EX2_CONDUCTORES] (
  CONDUCTOR_ID INT IDENTITY(1,1) NOT NULL,
  PATERNO VARCHAR(45) NOT NULL,
  MATERNO VARCHAR(45) NULL,
  NOMBRES VARCHAR(45) NOT NULL,
  NUM_LICENCIA VARCHAR(45) NOT NULL,
  TIPO_LICENCIA_ID INT NOT NULL,
  PUNTOS_ACUMULADOS INT NOT NULL,
  PRIMARY KEY (CONDUCTOR_ID),
  INDEX fk_EX2_CONDUCTORES_EX2_TIPOS_LICENCIAS_idx (TIPO_LICENCIA_ID ASC),
  CONSTRAINT fk_EX2_CONDUCTORES_EX2_TIPOS_LICENCIAS
    FOREIGN KEY (TIPO_LICENCIA_ID)
    REFERENCES [dbo].[EX2_TIPOS_LICENCIAS](TIPO_LICENCIA_ID)
);

DROP TABLE IF EXISTS [dbo].[EX2_VEHICULOS];

CREATE TABLE  [dbo].[EX2_VEHICULOS] (
  VEHICULO_ID INT IDENTITY(1,1) NOT NULL,
  PLACA CHAR(7) NOT NULL,
  MARCA VARCHAR(45) NOT NULL,
  MODELO VARCHAR(45) NOT NULL,
  ANHO INT NOT NULL,
  PRIMARY KEY (VEHICULO_ID)
);

DROP TABLE IF EXISTS [dbo].[EX2_INFRACCIONES] ;

CREATE TABLE [dbo].[EX2_INFRACCIONES] (
  INFRACCION_ID INT NOT NULL,
  DESCRIPCION VARCHAR(45) NOT NULL,
  MONTO_MULTA DECIMAL(10,3) NOT NULL,
  GRAVEDAD VARCHAR(10) CHECK (GRAVEDAD IN ('LEVE', 'GRAVE', 'MUY_GRAVE')) NOT NULL,
  PUNTOS INT NOT NULL,
  PRIMARY KEY (INFRACCION_ID)
);

DROP TABLE IF EXISTS [dbo].[EX2_REPORTES_INFRACCIONES];

CREATE TABLE [dbo].[EX2_REPORTES_INFRACCIONES] (
  REPORTE_ID INT IDENTITY(1,1) NOT NULL,
  CONDUCTOR_ID INT NOT NULL,
  PATERNO VARCHAR(45) NOT NULL,
  MATERNO VARCHAR(45) NULL,
  NOMBRES VARCHAR(45) NOT NULL,
  VEHICULO_ID INT NOT NULL,
  PLACA CHAR(7) NOT NULL,
  MARCA VARCHAR(45) NOT NULL,
  MODELO VARCHAR(45) NOT NULL,
  ANHO INT NOT NULL,
  INFRACCION_ID INT NOT NULL,
  DESCRIPCION VARCHAR(255) NOT NULL,
  MONTO DECIMAL(10,3) NOT NULL,
  GRAVEDAD VARCHAR(45) NOT NULL,
  PRIMARY KEY (REPORTE_ID),
  INDEX fk_EX2_REPORTES_INFRACCIONES_EX2_CONDUCTORES1_idx (CONDUCTOR_ID ASC),
  INDEX fk_EX2_REPORTES_INFRACCIONES_EX2_VEHICULOS1_idx (VEHICULO_ID ASC),
  INDEX fk_EX2_REPORTES_INFRACCIONES_EX2_INFRACCIONES1_idx (INFRACCION_ID ASC),
  CONSTRAINT fk_EX2_REPORTES_INFRACCIONES_EX2_CONDUCTORES1
    FOREIGN KEY (CONDUCTOR_ID)
    REFERENCES [dbo].[EX2_CONDUCTORES] (CONDUCTOR_ID),
  CONSTRAINT fk_EX2_REPORTES_INFRACCIONES_EX2_VEHICULOS1
    FOREIGN KEY (VEHICULO_ID)
    REFERENCES [dbo].[EX2_VEHICULOS] (VEHICULO_ID),
  CONSTRAINT fk_EX2_REPORTES_INFRACCIONES_EX2_INFRACCIONES1
    FOREIGN KEY (INFRACCION_ID)
    REFERENCES [dbo].[EX2_INFRACCIONES] (INFRACCION_ID)
);

DROP TABLE IF EXISTS [dbo].[EX2_VEHICULOS_POR_CONDUCTOR];

CREATE TABLE [dbo].[EX2_VEHICULOS_POR_CONDUCTOR] (
  VEHICULO_ID INT NOT NULL,
  CONDUCTOR_ID INT NOT NULL,
  FECHA_ADQUISICION DATE NOT NULL,
  PRIMARY KEY (VEHICULO_ID, CONDUCTOR_ID),
  INDEX fk_EX2_VEHICULOS_POR_CONDUCTOR_EX2_VEHICULOS1_idx (VEHICULO_ID ASC),
  CONSTRAINT fk_EX2_VEHICULOS_POR_CONDUCTOR_EX2_CONDUCTORES1
    FOREIGN KEY (CONDUCTOR_ID)
    REFERENCES [dbo].[EX2_CONDUCTORES] (CONDUCTOR_ID),
  CONSTRAINT fk_EX2_VEHICULOS_POR_CONDUCTOR_EX2_VEHICULOS1
    FOREIGN KEY (VEHICULO_ID)
    REFERENCES [dbo].[EX2_VEHICULOS] (VEHICULO_ID)
);

DROP TABLE IF EXISTS [dbo].[EX2_REGISTRO_INFRACCIONES];

CREATE TABLE [dbo].[EX2_REGISTRO_INFRACCIONES] (
  FECHA DATE NOT NULL,
  VEHICULO_ID INT NOT NULL,
  CONDUCTOR_ID INT NOT NULL,
  INFRACCION_ID INT NOT NULL,
  PRIMARY KEY (FECHA, VEHICULO_ID, CONDUCTOR_ID, INFRACCION_ID),
  INDEX fk_EX2_REGISTRO_INFRACCIONES_EX2_INFRACCIONES1_idx (INFRACCION_ID ASC),
  CONSTRAINT fk_EX2_REGISTRO_INFRACCIONES_EX2_VEHICULOS_POR_CONDUCTOR1
    FOREIGN KEY (VEHICULO_ID, CONDUCTOR_ID)
    REFERENCES [dbo].[EX2_VEHICULOS_POR_CONDUCTOR] (VEHICULO_ID , CONDUCTOR_ID),
  CONSTRAINT fk_EX2_REGISTRO_INFRACCIONES_EX2_INFRACCIONES1
    FOREIGN KEY (INFRACCION_ID)
    REFERENCES [dbo].[EX2_INFRACCIONES] (INFRACCION_ID)
);