-- Tabla: EX2_TIPOS_LICENCIAS
INSERT INTO [dbo].EX2_TIPOS_LICENCIAS (TIPO_LICENCIA_ID, NOMBRE, DESCRIPCION) VALUES
(1, 'A-I', 'Motocicletas'),
(2, 'A-II', 'Automóviles'),
(3, 'A-III', 'Camiones y buses');

-- Tabla: EX2_CONDUCTORES
INSERT INTO [dbo].EX2_CONDUCTORES (PATERNO, MATERNO, NOMBRES, NUM_LICENCIA, TIPO_LICENCIA_ID, PUNTOS_ACUMULADOS) VALUES
('Pérez', 'Gómez', 'Luis', 'A123456', 2, 50),
('Rodríguez', NULL, 'Ana', 'B234567', 1, 30);

-- Tabla: EX2_VEHICULOS
INSERT INTO [dbo].EX2_VEHICULOS (PLACA, MARCA, MODELO, ANHO) VALUES
('ABC1234', 'Toyota', 'Corolla', 2020),
('XYZ5678', 'Honda', 'Civic', 2022);

-- Tabla: EX2_INFRACCIONES
INSERT INTO [dbo].EX2_INFRACCIONES (INFRACCION_ID, DESCRIPCION, MONTO_MULTA, GRAVEDAD, PUNTOS) VALUES
(1, 'Exceso de velocidad', 500.000, 'GRAVE', 20),
(2, 'Conducir sin luces', 150.000, 'LEVE', 5);

-- Tabla: EX2_REPORTES_INFRACCIONES
INSERT INTO [dbo].EX2_REPORTES_INFRACCIONES (CONDUCTOR_ID, PATERNO, MATERNO, NOMBRES, VEHICULO_ID, PLACA, MARCA, MODELO, ANHO, INFRACCION_ID, DESCRIPCION, MONTO, GRAVEDAD) VALUES
(1, 'Pérez', 'Gómez', 'Luis', 1, 'ABC1234', 'Toyota', 'Corolla', 2020, 1, 'Exceso de velocidad', 500.000, 'GRAVE');

-- Tabla: EX2_VEHICULOS_POR_CONDUCTOR
INSERT INTO [dbo].EX2_VEHICULOS_POR_CONDUCTOR (VEHICULO_ID, CONDUCTOR_ID, FECHA_ADQUISICION) VALUES
(1, 1, '2023-01-15'),
(2, 2, '2024-05-20');

-- Tabla: EX2_REGISTRO_INFRACCIONES
INSERT INTO [dbo].EX2_REGISTRO_INFRACCIONES (FECHA, VEHICULO_ID, CONDUCTOR_ID, INFRACCION_ID) VALUES
('2024-06-10', 1, 1, 1),
('2024-07-05', 2, 2, 2);
