//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitSoftBO.TransitSoftWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", ConfigurationName="TransitSoftWS.TipoLicenciaWS")]
    public interface TipoLicenciaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.transitsoft.pucp.edu.pe/TipoLicenciaWS/listarTiposLicenciaRequest" +
            "", ReplyAction="http://services.transitsoft.pucp.edu.pe/TipoLicenciaWS/listarTiposLicenciaRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBO.TransitSoftWS.listarTiposLicenciaResponse listarTiposLicencia(TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.transitsoft.pucp.edu.pe/TipoLicenciaWS/listarTiposLicenciaRequest" +
            "", ReplyAction="http://services.transitsoft.pucp.edu.pe/TipoLicenciaWS/listarTiposLicenciaRespons" +
            "e")]
        System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.listarTiposLicenciaResponse> listarTiposLicenciaAsync(TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/")]
    public partial class tipoLicencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoLicenciaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoLicencia {
            get {
                return this.idTipoLicenciaField;
            }
            set {
                this.idTipoLicenciaField = value;
                this.RaisePropertyChanged("idTipoLicencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/")]
    public partial class conductor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private int idConductorField;
        
        private string nombresField;
        
        private string numeroLicenciaField;
        
        private int puntosAcumuladosField;
        
        private tipoLicencia tipoLicenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idConductor {
            get {
                return this.idConductorField;
            }
            set {
                this.idConductorField = value;
                this.RaisePropertyChanged("idConductor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroLicencia {
            get {
                return this.numeroLicenciaField;
            }
            set {
                this.numeroLicenciaField = value;
                this.RaisePropertyChanged("numeroLicencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int puntosAcumulados {
            get {
                return this.puntosAcumuladosField;
            }
            set {
                this.puntosAcumuladosField = value;
                this.RaisePropertyChanged("puntosAcumulados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoLicencia tipoLicencia {
            get {
                return this.tipoLicenciaField;
            }
            set {
                this.tipoLicenciaField = value;
                this.RaisePropertyChanged("tipoLicencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/")]
    public partial class vehiculoConductor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private conductor conductorField;
        
        private System.DateTime fechaAdquisicionField;
        
        private bool fechaAdquisicionFieldSpecified;
        
        private vehiculo vehiculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public conductor conductor {
            get {
                return this.conductorField;
            }
            set {
                this.conductorField = value;
                this.RaisePropertyChanged("conductor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaAdquisicion {
            get {
                return this.fechaAdquisicionField;
            }
            set {
                this.fechaAdquisicionField = value;
                this.RaisePropertyChanged("fechaAdquisicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAdquisicionSpecified {
            get {
                return this.fechaAdquisicionFieldSpecified;
            }
            set {
                this.fechaAdquisicionFieldSpecified = value;
                this.RaisePropertyChanged("fechaAdquisicionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public vehiculo vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
                this.RaisePropertyChanged("vehiculo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/")]
    public partial class vehiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anhoField;
        
        private int idVehiculoField;
        
        private string marcaField;
        
        private string modeloField;
        
        private string placaField;
        
        private vehiculoConductor vehiculosConductoresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anho {
            get {
                return this.anhoField;
            }
            set {
                this.anhoField = value;
                this.RaisePropertyChanged("anho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idVehiculo {
            get {
                return this.idVehiculoField;
            }
            set {
                this.idVehiculoField = value;
                this.RaisePropertyChanged("idVehiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public vehiculoConductor vehiculosConductores {
            get {
                return this.vehiculosConductoresField;
            }
            set {
                this.vehiculosConductoresField = value;
                this.RaisePropertyChanged("vehiculosConductores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposLicencia", WrapperNamespace="http://services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposLicenciaRequest {
        
        public listarTiposLicenciaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposLicenciaResponse", WrapperNamespace="http://services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposLicenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBO.TransitSoftWS.tipoLicencia[] @return;
        
        public listarTiposLicenciaResponse() {
        }
        
        public listarTiposLicenciaResponse(TransitSoftBO.TransitSoftWS.tipoLicencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoLicenciaWSChannel : TransitSoftBO.TransitSoftWS.TipoLicenciaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoLicenciaWSClient : System.ServiceModel.ClientBase<TransitSoftBO.TransitSoftWS.TipoLicenciaWS>, TransitSoftBO.TransitSoftWS.TipoLicenciaWS {
        
        public TipoLicenciaWSClient() {
        }
        
        public TipoLicenciaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoLicenciaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoLicenciaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoLicenciaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBO.TransitSoftWS.listarTiposLicenciaResponse TransitSoftBO.TransitSoftWS.TipoLicenciaWS.listarTiposLicencia(TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest request) {
            return base.Channel.listarTiposLicencia(request);
        }
        
        public TransitSoftBO.TransitSoftWS.tipoLicencia[] listarTiposLicencia() {
            TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest inValue = new TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest();
            TransitSoftBO.TransitSoftWS.listarTiposLicenciaResponse retVal = ((TransitSoftBO.TransitSoftWS.TipoLicenciaWS)(this)).listarTiposLicencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.listarTiposLicenciaResponse> TransitSoftBO.TransitSoftWS.TipoLicenciaWS.listarTiposLicenciaAsync(TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest request) {
            return base.Channel.listarTiposLicenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.listarTiposLicenciaResponse> listarTiposLicenciaAsync() {
            TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest inValue = new TransitSoftBO.TransitSoftWS.listarTiposLicenciaRequest();
            return ((TransitSoftBO.TransitSoftWS.TipoLicenciaWS)(this)).listarTiposLicenciaAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", ConfigurationName="TransitSoftWS.VehiculoWS")]
    public interface VehiculoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.transitsoft.pucp.edu.pe/VehiculoWS/listarVehiculosPorPlacaRequest" +
            "", ReplyAction="http://services.transitsoft.pucp.edu.pe/VehiculoWS/listarVehiculosPorPlacaRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaResponse listarVehiculosPorPlaca(TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.transitsoft.pucp.edu.pe/VehiculoWS/listarVehiculosPorPlacaRequest" +
            "", ReplyAction="http://services.transitsoft.pucp.edu.pe/VehiculoWS/listarVehiculosPorPlacaRespons" +
            "e")]
        System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaResponse> listarVehiculosPorPlacaAsync(TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVehiculosPorPlaca", WrapperNamespace="http://services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVehiculosPorPlacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string placa;
        
        public listarVehiculosPorPlacaRequest() {
        }
        
        public listarVehiculosPorPlacaRequest(string placa) {
            this.placa = placa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVehiculosPorPlacaResponse", WrapperNamespace="http://services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarVehiculosPorPlacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBO.TransitSoftWS.vehiculo[] @return;
        
        public listarVehiculosPorPlacaResponse() {
        }
        
        public listarVehiculosPorPlacaResponse(TransitSoftBO.TransitSoftWS.vehiculo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehiculoWSChannel : TransitSoftBO.TransitSoftWS.VehiculoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoWSClient : System.ServiceModel.ClientBase<TransitSoftBO.TransitSoftWS.VehiculoWS>, TransitSoftBO.TransitSoftWS.VehiculoWS {
        
        public VehiculoWSClient() {
        }
        
        public VehiculoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaResponse TransitSoftBO.TransitSoftWS.VehiculoWS.listarVehiculosPorPlaca(TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest request) {
            return base.Channel.listarVehiculosPorPlaca(request);
        }
        
        public TransitSoftBO.TransitSoftWS.vehiculo[] listarVehiculosPorPlaca(string placa) {
            TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest inValue = new TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest();
            inValue.placa = placa;
            TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaResponse retVal = ((TransitSoftBO.TransitSoftWS.VehiculoWS)(this)).listarVehiculosPorPlaca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaResponse> TransitSoftBO.TransitSoftWS.VehiculoWS.listarVehiculosPorPlacaAsync(TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest request) {
            return base.Channel.listarVehiculosPorPlacaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaResponse> listarVehiculosPorPlacaAsync(string placa) {
            TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest inValue = new TransitSoftBO.TransitSoftWS.listarVehiculosPorPlacaRequest();
            inValue.placa = placa;
            return ((TransitSoftBO.TransitSoftWS.VehiculoWS)(this)).listarVehiculosPorPlacaAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", ConfigurationName="TransitSoftWS.ConductorWS")]
    public interface ConductorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.transitsoft.pucp.edu.pe/ConductorWS/insertarConductorRequest", ReplyAction="http://services.transitsoft.pucp.edu.pe/ConductorWS/insertarConductorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TransitSoftBO.TransitSoftWS.insertarConductorResponse insertarConductor(TransitSoftBO.TransitSoftWS.insertarConductorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.transitsoft.pucp.edu.pe/ConductorWS/insertarConductorRequest", ReplyAction="http://services.transitsoft.pucp.edu.pe/ConductorWS/insertarConductorResponse")]
        System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.insertarConductorResponse> insertarConductorAsync(TransitSoftBO.TransitSoftWS.insertarConductorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarConductor", WrapperNamespace="http://services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarConductorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBO.TransitSoftWS.conductor conductor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("vehiculos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitSoftBO.TransitSoftWS.vehiculoConductor[] vehiculos;
        
        public insertarConductorRequest() {
        }
        
        public insertarConductorRequest(TransitSoftBO.TransitSoftWS.conductor conductor, TransitSoftBO.TransitSoftWS.vehiculoConductor[] vehiculos) {
            this.conductor = conductor;
            this.vehiculos = vehiculos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarConductorResponse", WrapperNamespace="http://services.transitsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarConductorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.transitsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarConductorResponse() {
        }
        
        public insertarConductorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConductorWSChannel : TransitSoftBO.TransitSoftWS.ConductorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConductorWSClient : System.ServiceModel.ClientBase<TransitSoftBO.TransitSoftWS.ConductorWS>, TransitSoftBO.TransitSoftWS.ConductorWS {
        
        public ConductorWSClient() {
        }
        
        public ConductorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConductorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConductorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConductorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransitSoftBO.TransitSoftWS.insertarConductorResponse TransitSoftBO.TransitSoftWS.ConductorWS.insertarConductor(TransitSoftBO.TransitSoftWS.insertarConductorRequest request) {
            return base.Channel.insertarConductor(request);
        }
        
        public int insertarConductor(TransitSoftBO.TransitSoftWS.conductor conductor, TransitSoftBO.TransitSoftWS.vehiculoConductor[] vehiculos) {
            TransitSoftBO.TransitSoftWS.insertarConductorRequest inValue = new TransitSoftBO.TransitSoftWS.insertarConductorRequest();
            inValue.conductor = conductor;
            inValue.vehiculos = vehiculos;
            TransitSoftBO.TransitSoftWS.insertarConductorResponse retVal = ((TransitSoftBO.TransitSoftWS.ConductorWS)(this)).insertarConductor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.insertarConductorResponse> TransitSoftBO.TransitSoftWS.ConductorWS.insertarConductorAsync(TransitSoftBO.TransitSoftWS.insertarConductorRequest request) {
            return base.Channel.insertarConductorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransitSoftBO.TransitSoftWS.insertarConductorResponse> insertarConductorAsync(TransitSoftBO.TransitSoftWS.conductor conductor, TransitSoftBO.TransitSoftWS.vehiculoConductor[] vehiculos) {
            TransitSoftBO.TransitSoftWS.insertarConductorRequest inValue = new TransitSoftBO.TransitSoftWS.insertarConductorRequest();
            inValue.conductor = conductor;
            inValue.vehiculos = vehiculos;
            return ((TransitSoftBO.TransitSoftWS.ConductorWS)(this)).insertarConductorAsync(inValue);
        }
    }
}
